### ISSUE TITLE
Constant repeatable crash with this mod

### ISSUE THREAD

**Issue by Sunconure11** [Flomik10002/RespiteCreatorsFabric#1]
https://pastebin.com/0zH723CZ

Trying to use this mod causes this issue.

**Comment by Flomik10002** [comment]
> https://pastebin.com/0zH723CZ
> 
> 
> 
> Trying to use this mod causes this issue.

I don’t think that this can be caused by my mod, in my mod I don’t use a similar injection method, I can recommend installing java 17, because everything is fine when checking and playing on it

**Comment by Sunconure11** [comment]
I have the appropriate Java version, so I don't think that is it.

**Comment by Sunconure11** [comment]
However, I will try and get more info on it for you

**Comment by Sunconure11** [comment]
Looks like it went away. Strange.

**Comment by Sunconure11** [comment]
I think this is still present, but I don't know what mod gives this mod issues.

**Comment by Flomik10002** [comment]
> I think this is still present, but I don't know what mod gives this mod issues.

As I understand, create or something like this wrong working with something. Maybe you can try to find mistakes with mod "Mixin trace" and send it to me

**Comment by Sunconure11** [comment]
Hm, do you have Discord? I can direct you to a server that may be able to help a bit more.

**Comment by Sunconure11** [comment]
Wait, I think I have a hunch.

https://pastebin.com/QMVxjwan

**Comment by Sunconure11** [comment]
Enderchests, for whatever reason.

**Comment by Sunconure11** [comment]
https://discord.gg/KrqaWY4M <- Farmer's Delight Discord

https://discord.gg/ddRBRk5P <- Create Addon Discord

**Comment by Flomik10002** [comment]
> Enderchests, for whatever reason.

I can see a many mistakes caused by create, try to use other build/version of create mod

**Comment by Sunconure11** [comment]
Turning off Ender Chests seems to have solved the issue. Though I'm not sure why.
