### ISSUE TITLE
[Compat] Compatibility with Farmer's Delight Refabricated [Fabric 1.20.1]

### ISSUE THREAD

**Issue by NolanHewitt** [Flomik10002/RespiteCreatorsFabric#4]
Compatibility for the new Farmer's Delight port:

https://www.curseforge.com/minecraft/mc-mods/farmers-delight-refabricated?

It offers more support for a better port which is more faithful to the original mod on Forge, and is cleaner internally and has less bugs.

**Comment by Flomik10002** [comment]
Finally I made full support for the refabricated mod
